const dummyProfiles = [
  {
    id: 1,
    name: "Alice",
    age: 24,
    bio: "Loves hiking 🌄",
    avatar: "https://i.pravatar.cc/300?img=1",
  },
  {
    id: 2,
    name: "Bob",
    age: 27,
    bio: "Coffee addict ☕",
    avatar: "https://i.pravatar.cc/300?img=2",
  },
  {
    id: 3,
    name: "Charlie",
    age: 22,
    bio: "Music is life 🎶",
    avatar: "https://i.pravatar.cc/300?img=3",
  },
  {
    id: 4,
    name: "Diana",
    age: 26,
    bio: "Frontend wizard ✨",
    avatar: "https://i.pravatar.cc/300?img=4",
  },
  {
    id: 5,
    name: "Ethan",
    age: 29,
    bio: "Backend thinker 💻",
    avatar: "https://i.pravatar.cc/300?img=5",
  },
  {
    id: 6,
    name: "Fiona",
    age: 23,
    bio: "AI & ML explorer 🤖",
    avatar: "https://i.pravatar.cc/300?img=6",
  },
  {
    id: 7,
    name: "George",
    age: 28,
    bio: "Open source contributor 🌍",
    avatar: "https://i.pravatar.cc/300?img=7",
  },
  {
    id: 8,
    name: "Hannah",
    age: 25,
    bio: "UI/UX designer 🎨",
    avatar: "https://i.pravatar.cc/300?img=8",
  },
  {
    id: 9,
    name: "Ian",
    age: 30,
    bio: "Cloud architect ☁️",
    avatar: "https://i.pravatar.cc/300?img=9",
  },
  {
    id: 10,
    name: "Jasmine",
    age: 21,
    bio: "Student & part-time coder 📚",
    avatar: "https://i.pravatar.cc/300?img=10",
  },
  {
    id: 11,
    name: "Kevin",
    age: 27,
    bio: "Cybersecurity geek 🔐",
    avatar: "https://i.pravatar.cc/300?img=11",
  },
  {
    id: 12,
    name: "Lily",
    age: 24,
    bio: "Full-stack developer ⚡",
    avatar: "https://i.pravatar.cc/300?img=12",
  },
  {
    id: 13,
    name: "Michael",
    age: 26,
    bio: "Gamer + coder 🎮",
    avatar: "https://i.pravatar.cc/300?img=13",
  },
  {
    id: 14,
    name: "Nina",
    age: 22,
    bio: "Blockchain enthusiast ⛓️",
    avatar: "https://i.pravatar.cc/300?img=14",
  },
  {
    id: 15,
    name: "Oscar",
    age: 28,
    bio: "Startup founder 🚀",
    avatar: "https://i.pravatar.cc/300?img=15",
  },
  {
    id: 16,
    name: "Priya",
    age: 23,
    bio: "Data scientist 📊",
    avatar: "https://i.pravatar.cc/300?img=16",
  },
  {
    id: 17,
    name: "Quinn",
    age: 25,
    bio: "VR/AR dreamer 🕶️",
    avatar: "https://i.pravatar.cc/300?img=17",
  },
  {
    id: 18,
    name: "Ravi",
    age: 29,
    bio: "DevOps & automation ⚙️",
    avatar: "https://i.pravatar.cc/300?img=18",
  },
  {
    id: 19,
    name: "Sophia",
    age: 21,
    bio: "Mobile app builder 📱",
    avatar: "https://i.pravatar.cc/300?img=19",
  },
  {
    id: 20,
    name: "Thomas",
    age: 28,
    bio: "Big data analyst 📡",
    avatar: "https://i.pravatar.cc/300?img=20",
  },
  {
    id: 21,
    name: "Uma",
    age: 24,
    bio: "Product manager 📌",
    avatar: "https://i.pravatar.cc/300?img=21",
  },
  {
    id: 22,
    name: "Victor",
    age: 27,
    bio: "Game dev in Unity 🕹️",
    avatar: "https://i.pravatar.cc/300?img=22",
  },
  {
    id: 23,
    name: "Wendy",
    age: 26,
    bio: "Robotics tinkerer 🤖",
    avatar: "https://i.pravatar.cc/300?img=23",
  },
  {
    id: 24,
    name: "Xavier",
    age: 30,
    bio: "AI ethics researcher 🧠",
    avatar: "https://i.pravatar.cc/300?img=24",
  },
  {
    id: 25,
    name: "Yara",
    age: 22,
    bio: "Creative coder 🎭",
    avatar: "https://i.pravatar.cc/300?img=25",
  },
  {
    id: 26,
    name: "Zane",
    age: 23,
    bio: "Rustacean 🦀",
    avatar: "https://i.pravatar.cc/300?img=26",
  },
  {
    id: 27,
    name: "Amira",
    age: 28,
    bio: "Kotlin lover 💜",
    avatar: "https://i.pravatar.cc/300?img=27",
  },
  {
    id: 28,
    name: "Brian",
    age: 24,
    bio: "Cloud native ☁️",
    avatar: "https://i.pravatar.cc/300?img=28",
  },
  {
    id: 29,
    name: "Clara",
    age: 25,
    bio: "Design systems nerd 🎨",
    avatar: "https://i.pravatar.cc/300?img=29",
  },
  {
    id: 30,
    name: "Diego",
    age: 27,
    bio: "React Native wizard 📱",
    avatar: "https://i.pravatar.cc/300?img=30",
  },
  {
    id: 31,
    name: "Elena",
    age: 22,
    bio: "Quantum computing curious ⚛️",
    avatar: "https://i.pravatar.cc/300?img=31",
  },
  {
    id: 32,
    name: "Farid",
    age: 29,
    bio: "API builder 🔌",
    avatar: "https://i.pravatar.cc/300?img=32",
  },
  {
    id: 33,
    name: "Grace",
    age: 26,
    bio: "Web3 explorer 🌐",
    avatar: "https://i.pravatar.cc/300?img=33",
  },
  {
    id: 34,
    name: "Hiro",
    age: 28,
    bio: "Anime + coding fan 🎌",
    avatar: "https://i.pravatar.cc/300?img=34",
  },
  {
    id: 35,
    name: "Isabella",
    age: 24,
    bio: "Accessibility advocate ♿",
    avatar: "https://i.pravatar.cc/300?img=35",
  },
  {
    id: 36,
    name: "Jonas",
    age: 27,
    bio: "TypeScript all the way 🟦",
    avatar: "https://i.pravatar.cc/300?img=36",
  },
  {
    id: 37,
    name: "Kira",
    age: 23,
    bio: "Digital nomad ✈️",
    avatar: "https://i.pravatar.cc/300?img=37",
  },
  {
    id: 38,
    name: "Leo",
    age: 29,
    bio: "Pythonista 🐍",
    avatar: "https://i.pravatar.cc/300?img=38",
  },
  {
    id: 39,
    name: "Maya",
    age: 22,
    bio: "React fangirl ⚛️",
    avatar: "https://i.pravatar.cc/300?img=39",
  },
  {
    id: 40,
    name: "Noah",
    age: 28,
    bio: "Go developer 🐹",
    avatar: "https://i.pravatar.cc/300?img=40",
  },
  {
    id: 41,
    name: "Olivia",
    age: 25,
    bio: "Startup hustler 💡",
    avatar: "https://i.pravatar.cc/300?img=41",
  },
  {
    id: 42,
    name: "Pavel",
    age: 30,
    bio: "C++ systems engineer ⚙️",
    avatar: "https://i.pravatar.cc/300?img=42",
  },
  {
    id: 43,
    name: "Queenie",
    age: 24,
    bio: "Creative frontend dev 🎨",
    avatar: "https://i.pravatar.cc/300?img=43",
  },
  {
    id: 44,
    name: "Raj",
    age: 26,
    bio: "ML researcher 📈",
    avatar: "https://i.pravatar.cc/300?img=44",
  },
  {
    id: 45,
    name: "Sara",
    age: 21,
    bio: "Hackathon addict 🏆",
    avatar: "https://i.pravatar.cc/300?img=45",
  },
  {
    id: 46,
    name: "Tariq",
    age: 27,
    bio: "Linux power user 🐧",
    avatar: "https://i.pravatar.cc/300?img=46",
  },
  {
    id: 47,
    name: "Una",
    age: 23,
    bio: "VR/Metaverse creator 🌌",
    avatar: "https://i.pravatar.cc/300?img=47",
  },
  {
    id: 48,
    name: "Victor",
    age: 28,
    bio: "Security researcher 🔍",
    avatar: "https://i.pravatar.cc/300?img=48",
  },
  {
    id: 49,
    name: "Willow",
    age: 22,
    bio: "Indie hacker 💻",
    avatar: "https://i.pravatar.cc/300?img=49",
  },
  {
    id: 50,
    name: "Xena",
    age: 25,
    bio: "Game dev & pixel artist 🎮",
    avatar: "https://i.pravatar.cc/300?img=50",
  },
];

export default dummyProfiles;
